import localFont from "next/font/local";
import "./globals.css";
import { Poppins } from 'next/font/google';

// Load Poppins font with specific weights and styles
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // Add the weights you want
  style: ['normal', 'italic'], // Optional styles
  display: 'swap', // Optional font display property
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
